name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  type: # change this
    required: true
    description: 'type of installer'
    default: ''
  edt_version:
    required: false
    description: 'type of installer'
    default: '2022.2.5'
  onec_version:
    required: false
    description: 'type of installer'
    default: '8.3.20.1549'
  oneget_version:
    required: false
    description: 'type of installer'
    default: 'v0.6.0'
  cache:
    required: false
    description: 'use cache'
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'
